# Generated by Django 5.0.1 on 2024-02-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muzicar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Angazman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto_odrzavanja', models.CharField(max_length=100)),
                ('vrijeme', models.CharField(max_length=100)),
                ('datum', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('muzicar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.muzicar')),
            ],
        ),
    ]
