# Generated by Django 5.0.1 on 2024-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_muzicar_angazman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angazovanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=100)),
                ('mjesto_zurke', models.CharField(max_length=100)),
                ('vrijeme', models.CharField(max_length=50)),
                ('datum', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('muzicar', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Angazman',
        ),
        migrations.DeleteModel(
            name='Muzicar',
        ),
    ]
