# Generated by Django 5.0.1 on 2024-02-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_angazovanje_delete_angazman_delete_muzicar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angazovanje',
            old_name='ime_prezime',
            new_name='imePrezime',
        ),
        migrations.RenameField(
            model_name='angazovanje',
            old_name='mjesto_zurke',
            new_name='mjestoZurke',
        ),
    ]
