# Generated by Django 5.0.1 on 2024-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_ime_prezime_angazovanje_imeprezime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angazovanje',
            name='muzicar',
            field=models.CharField(choices=[('Jole', 'DJ Jole'), ('Pedja', 'Peđa Vukićević'), ('Obojica', 'DJ Jole i Peđa Vukićević')], max_length=100),
        ),
    ]
