# Generated by Django 5.0.1 on 2024-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_angazovanje_muzicar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angazovanje',
            old_name='imePrezime',
            new_name='ime_prezime',
        ),
        migrations.RenameField(
            model_name='angazovanje',
            old_name='mjestoZurke',
            new_name='mjesto_zurke',
        ),
        migrations.AlterField(
            model_name='angazovanje',
            name='muzicar',
            field=models.CharField(max_length=50),
        ),
    ]
