# Generated by Django 5.0.1 on 2024-02-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slika',
            new_name='SlikeNastupi',
        ),
    ]
