# Generated by Django 5.0.1 on 2024-02-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_slika_slikenastupi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='imagesForSongs/')),
                ('audio_file', models.FileField(upload_to='songs/')),
            ],
        ),
    ]
