# Generated by Django 5.0.1 on 2024-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_song_allow_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery_videos/')),
            ],
        ),
    ]
