# Generated by Django 5.0.1 on 2024-02-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_galleryitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryItem',
        ),
    ]
