# Generated by Django 5.0.1 on 2024-02-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('tip', models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video')], default='IMG', max_length=3)),
                ('media_file', models.FileField(upload_to='media_files/')),
                ('kategorija', models.CharField(max_length=50)),
            ],
        ),
    ]
